### Home API
GET http://localhost:8080/

###

### Get all users
GET http://localhost:8080/users

###

### Create User - John
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Johnty Doe",
  "email": "john@example.com"
}

### Create Product for User
POST http://localhost:8080/products/user/1
Content-Type: application/json

{
    "name": "Mobile",
    "price": 25000
}

### Get All Products
GET http://localhost:8080/products


### Update Product
PUT http://localhost:8080/products/1
Content-Type: application/json

{
    "name": "Gaming Laptop",
    "price": 95000
}

### Delete Product
DELETE http://localhost:8080/products/1





